dist: xenial
language: rust
rust: stable

stages:
  - format
  - clippy
  - test
  - doc

jobs:
  include:
    - stage: format
      before_script:
        - rustup component add rustfmt
      script:
        - rustfmt --edition=2018 src/lib.rs --check
        - rustfmt --edition=2018 src/main.rs --check
    - stage: clippy
      before_script:
        - rustup toolchain install nightly-2020-01-02-x86_64-unknown-linux-gnu
        - rustup component add clippy --toolchain nightly-2020-01-02-x86_64-unknown-linux-gnu
      script:
        - cargo +nightly-2020-01-02 clippy
    - stage: test
      rust:
        - stable
        - beta
        - nightly
      os:
        - linux
        - osx
        - windows
      script:
        - cargo build --verbose --release
        - cargo test --verbose --release -- --nocapture
    - stage: doc
      script:
        - cargo doc --verbose --release

notifications:
  email:
    on_success: change
    on_failure: always
