language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

before_script:
  # Download dependency repositories
  - .travis/download.sh deepwell
  # Add rustfmt
  - rustup component add rustfmt
  # Add clippy
  - rustup toolchain install nightly-2020-01-02-x86_64-unknown-linux-gnu
  - rustup component add clippy --toolchain nightly-2020-01-02-x86_64-unknown-linux-gnu

script:
  # Ensure code is rustfmt'd
  - echo ======================================== rustfmt =======================================
  - rustfmt --edition=2018 src/lib.rs --check
  - rustfmt --edition=2018 src/main.rs --check
  # Check clippy lints
  - echo ======================================== clippy =======================================
  - cargo +nightly-2020-01-02 clippy
  # Run build
  - echo ======================================== build =======================================
  - cargo build --verbose --release
  - cargo test --verbose --release -- --nocapture
  # Build documentation
  - echo ======================================== docs =======================================
  - cargo doc --verbose --no-deps

jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: always
